# theme/default.nix — compositor-agnostic Wayland theming.
#
# Single active theme export. The structure stays extensible: future
# themes still live under theme/themes/<name>/ and can be wired here,
# but the current system intentionally supports only one active theme.
#
# Ownership model (runtime theme cutover 2026-07-10):
#   Nix owns:    packages, settings.ini (first-login defaults),
#                cursor theme, non-color structural config.
#   Caelestia:   live color state — dconf gtk-theme/icon-theme,
#                gtk-3.0/gtk.css + gtk-4.0/gtk.css (@define-color),
#                Hyprland scheme/current.conf, terminal sequences.
#   Rule:        one consumer = one color owner. Nix does not
#                generate gtk-4.0/gtk.css (Caelestia owns it).
#                Nix does not write dconf color-scheme (Caelestia
#                owns it). settings.ini values are first-login
#                defaults that dconf overrides at runtime.
#
# Aggregator: exports the theme's palette `p`, color helpers `c`,
# wallpaper path, and the full theme attrset to all submodules via
# _module.args. Submodules consume `theme` to generate component-
# specific config (rofi theme, etc. — ghostty colours are now
# runtime-owned by Caelestia CLI).
#
# Helper scripts (notification toggle, lecoo charge mode, etc.) live
# in theme/scripts.nix. Compositor-specific config (Hyprland keybinds,
# Caelestia shell lock/idle) lives in
# home/desktop/sessions/<name>/.
#
# Imported from home/desktop/default.nix when desktops is non-empty.
# Headless/server hosts never see this file.
{pkgs, ...}: let
  theme = import ./themes/monochrome/default.nix {};

  # Palette — extracted from the active theme for convenience.
  # Still used by rofi.nix for its rasi theme. Ghostty and Hyprland
  # colours are now runtime-owned by Caelestia CLI.
  p = theme.palette;

  # Color helpers — convert palette tokens into the surface formats
  # different consumers expect (Hyprland literals, rofi rasi rgba,
  # GTK rgba). Single source of truth.
  c = import ../lib/color.nix;

  # Wallpaper path — original full-resolution asset, used by the
  # Caelestia lock screen. Live wallpaper is owned by Caelestia shell
  # (caelestia wallpaper -f).
  wallpaper = "${theme.wallpaper}";
in {
  # _module.args makes p, c, wallpaper, and the full theme attrset
  # available as function arguments to ALL submodules imported below.
  # Submodules can destructure what they need:
  #   { pkgs, p, c, theme, ... }: { ... }
  _module.args = {
    inherit p c wallpaper theme;
  };

  imports = [
    ./scripts.nix
    ./ghostty.nix
    ./mako.nix
    ./rofi.nix
  ];

  # ── Cursor (Wayland-wide, session-level) ──────────────────────────────
  # home.pointerCursor sets XCURSOR_THEME/SIZE for the entire Wayland session,
  # installs theme to ~/.local/share/icons, and configures GTK/X11 fallback.
  # gtk.cursorTheme below is kept for GTK-specific overrides.
  home.pointerCursor = {
    name = "Capitaine Cursors (Gruvbox)";
    package = pkgs.capitaine-cursors-themed;
    size = 24;
    gtk.enable = true;
  };

  # ── dconf (GTK structural settings only) ──────────────────────────────
  # color-scheme is owned by Caelestia CLI (writes prefer-dark/prefer-light
  # based on active scheme mode). Nix must not overwrite it on rebuild.
  # Nautilus window-state is structural, not colour — Nix keeps it.
  dconf.settings = {
    "org/gnome/nautilus/window-state" = {
      maximized = false;
      initial-size = "(890, 550)";
    };
  };

  # ── GTK theme (framework + first-login defaults) ──────────────────────
  # Nix installs the adw-gtk3 package and writes settings.ini with
  # adw-gtk3-dark as the first-login default. Caelestia CLI writes
  # dconf gtk-theme at runtime (can switch to adw-gtk3-light for
  # light mode). dconf wins at runtime — settings.ini is a fallback.
  # gtk-4.0/gtk.css is NOT generated by HM — Caelestia CLI owns it
  # (@define-color CSS variables from the active scheme). GTK4 uses
  # libadwaita's built-in styling and reads @define-color variables
  # directly; the adw-gtk3 @import is only needed for GTK3 apps
  # (which read settings.ini → gtk-theme-name=adw-gtk3-dark).
  gtk = {
    enable = true;
    theme = {
      name = "adw-gtk3-dark";
      package = pkgs.adw-gtk3;
    };
    # Explicitly null — HM 26.05 with stateVersion < 26.05 defaults
    # gtk4.theme to config.gtk.theme, which generates gtk-4.0/gtk.css
    # as a Nix store symlink. This conflicts with Caelestia CLI's
    # plain file (oscillation on rebuild / scheme set). Setting null
    # stops HM from generating gtk-4.0/gtk.css entirely.
    gtk4.theme = null;
    cursorTheme = {
      name = "Capitaine Cursors (Gruvbox)";
      package = pkgs.capitaine-cursors-themed;
      size = 24;
    };
    iconTheme = {
      name = "Papirus-Dark";
      package = pkgs.papirus-icon-theme;
    };
  };

  # papirus-folders — enables Caelestia CLI's sync_papirus_colors()
  # which matches folder icon colours to the active scheme's primary
  # colour. Without this, the feature is a silent no-op.
  home.packages = [
    pkgs.papirus-folders
  ];
}
